/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ControlStatus = IDL.Variant({
  'notImplemented' : IDL.Null,
  'partiallyImplemented' : IDL.Null,
  'fullyImplemented' : IDL.Null,
  'notApplicable' : IDL.Null,
});
export const CreateComplianceControlInput = IDL.Record({
  'status' : ControlStatus,
  'controlName' : IDL.Text,
  'owner' : IDL.Text,
  'description' : IDL.Text,
  'frameworkId' : IDL.Nat,
  'controlId' : IDL.Text,
  'evidence' : IDL.Text,
});
export const GovernanceCategory = IDL.Variant({
  'actionItem' : IDL.Null,
  'committee' : IDL.Null,
  'meeting' : IDL.Null,
  'policy' : IDL.Null,
});
export const CreateGovernanceItemInput = IDL.Record({
  'title' : IDL.Text,
  'owner' : IDL.Text,
  'approvedBy' : IDL.Text,
  'reviewDate' : IDL.Text,
  'description' : IDL.Text,
  'category' : GovernanceCategory,
});
export const RiskTreatment = IDL.Variant({
  'accept' : IDL.Null,
  'avoid' : IDL.Null,
  'mitigate' : IDL.Null,
  'transfer' : IDL.Null,
});
export const MaturityLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'veryLow' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const MitigationControl = IDL.Record({
  'controlName' : IDL.Text,
  'maturityLevel' : MaturityLevel,
  'controlId' : IDL.Text,
});
export const ThreatCategory = IDL.Variant({
  'nonHostileOutsiders' : IDL.Null,
  'hostileInsiders' : IDL.Null,
  'legal' : IDL.Null,
  'dependencyProblems' : IDL.Null,
  'hostileOutsiders' : IDL.Null,
  'environmental' : IDL.Null,
  'technicalProblems' : IDL.Null,
  'nonHostileInsiders' : IDL.Null,
});
export const CreateRiskInput = IDL.Record({
  'treatmentNotes' : IDL.Text,
  'impact' : IDL.Nat,
  'title' : IDL.Text,
  'treatment' : RiskTreatment,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'mitigationControls' : IDL.Vec(MitigationControl),
  'vulnerability' : IDL.Text,
  'treatmentOwner' : IDL.Text,
  'treatmentPlanOwner' : IDL.Text,
  'threatCategory' : ThreatCategory,
  'treatmentPlanReviewDate' : IDL.Text,
  'treatmentPlanDescription' : IDL.Text,
  'likelihood' : IDL.Nat,
  'treatmentPlanTargetDate' : IDL.Text,
  'status' : IDL.Opt(IDL.Variant({'open': IDL.Null, 'closed': IDL.Null, 'inTreatment': IDL.Null})),
});
export const TenantCreateInput = IDL.Record({
  'domain' : IDL.Text,
  'name' : IDL.Text,
});
export const Tenant = IDL.Record({
  'id' : IDL.Nat,
  'domain' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const ComplianceControl = IDL.Record({
  'id' : IDL.Nat,
  'status' : ControlStatus,
  'controlName' : IDL.Text,
  'owner' : IDL.Text,
  'description' : IDL.Text,
  'frameworkId' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'controlId' : IDL.Text,
  'evidence' : IDL.Text,
});
export const ComplianceFramework = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'version' : IDL.Text,
});
export const ComplianceScores = IDL.Record({
  'frameworkName' : IDL.Text,
  'total' : IDL.Nat,
  'score' : IDL.Nat,
  'implemented' : IDL.Nat,
});
export const GovAttachmentMeta = IDL.Record({
  'blobUrl' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadedAt' : IDL.Int,
});
export const GovFrameworkMapping = IDL.Record({
  'frameworkName' : IDL.Text,
  'frameworkId' : IDL.Nat,
});
export const GovernanceStatus = IDL.Variant({
  'active' : IDL.Null,
  'underReview' : IDL.Null,
  'draft' : IDL.Null,
  'retired' : IDL.Null,
});
export const GovernanceItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : GovernanceStatus,
  'title' : IDL.Text,
  'owner' : IDL.Text,
  'approvedBy' : IDL.Text,
  'createdAt' : IDL.Int,
  'reviewDate' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'category' : GovernanceCategory,
});
export const GovernanceSummary = IDL.Record({
  'total' : IDL.Nat,
  'byStatus' : IDL.Vec(IDL.Tuple(GovernanceStatus, IDL.Nat)),
  'byCategory' : IDL.Vec(IDL.Tuple(GovernanceCategory, IDL.Nat)),
});
export const RiskStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inTreatment' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const RiskItem = IDL.Record({
  'id' : IDL.Nat,
  'treatmentNotes' : IDL.Text,
  'status' : RiskStatus,
  'impact' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'treatment' : RiskTreatment,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'mitigationControls' : IDL.Vec(MitigationControl),
  'tenantId' : IDL.Nat,
  'residualRiskScore' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'vulnerability' : IDL.Text,
  'treatmentOwner' : IDL.Text,
  'treatmentPlanOwner' : IDL.Text,
  'threatCategory' : ThreatCategory,
  'treatmentPlanReviewDate' : IDL.Text,
  'inherentRiskScore' : IDL.Nat,
  'treatmentPlanDescription' : IDL.Text,
  'likelihood' : IDL.Nat,
  'riskLevel' : RiskLevel,
  'treatmentPlanTargetDate' : IDL.Text,
});
export const RiskStats = IDL.Record({
  'avgResidualScore' : IDL.Nat,
  'total' : IDL.Nat,
  'byLevel' : IDL.Vec(IDL.Tuple(RiskLevel, IDL.Nat)),
  'avgInherentScore' : IDL.Nat,
  'byStatus' : IDL.Vec(IDL.Tuple(RiskStatus, IDL.Nat)),
});
export const SSOConfig = IDL.Record({
  'idpIssuerUrl' : IDL.Text,
  'idpClientId' : IDL.Text,
  'allowedDomains' : IDL.Vec(IDL.Text),
  'enabled' : IDL.Bool,
  'notes' : IDL.Text,
  'idpName' : IDL.Text,
  'requireDomainWhitelist' : IDL.Bool,
});
export const TenantOrg = IDL.Record({
  'id' : IDL.Text,
  'domain' : IDL.Text,
  'createdAt' : IDL.Int,
  'companyName' : IDL.Text,
});
export const UploadedDocumentMeta = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'blobUrl' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadedAt' : IDL.Int,
  'clauseNumber' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const TenantUser = IDL.Record({
  'id' : IDL.Text,
  'domain' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'approved' : IDL.Bool,
  'companyName' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const UserRegistrationInput = IDL.Record({
  'domain' : IDL.Text,
  'password' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
});
export const RegistrationResult = IDL.Variant({
  'ok' : IDL.Null,
  'userAlreadyExists' : IDL.Null,
  'invalidInput' : IDL.Null,
  'domainAlreadyRegistered' : IDL.Null,
});
export const TenantUserLoginResponse = IDL.Record({
  'id' : IDL.Text,
  'domain' : IDL.Text,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
});
export const TenantLoginResult = IDL.Variant({
  'ok' : TenantUserLoginResponse,
  'invalidEmail' : IDL.Null,
  'userNotFound' : IDL.Null,
  'invalidPassword' : IDL.Null,
  'internalError' : IDL.Null,
  'notApproved' : IDL.Null,
});
export const UpdateComplianceControlInput = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Opt(ControlStatus),
  'owner' : IDL.Opt(IDL.Text),
  'evidence' : IDL.Opt(IDL.Text),
});
export const UpdateGovernanceItemInput = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Opt(GovernanceStatus),
  'title' : IDL.Opt(IDL.Text),
  'owner' : IDL.Opt(IDL.Text),
  'approvedBy' : IDL.Opt(IDL.Text),
  'reviewDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(GovernanceCategory),
});
export const UpdateRiskInput = IDL.Record({
  'id' : IDL.Nat,
  'treatmentNotes' : IDL.Opt(IDL.Text),
  'impact' : IDL.Opt(IDL.Nat),
  'title' : IDL.Opt(IDL.Text),
  'treatment' : IDL.Opt(RiskTreatment),
  'dueDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'mitigationControls' : IDL.Opt(IDL.Vec(MitigationControl)),
  'vulnerability' : IDL.Opt(IDL.Text),
  'treatmentOwner' : IDL.Opt(IDL.Text),
  'treatmentPlanOwner' : IDL.Opt(IDL.Text),
  'threatCategory' : IDL.Opt(ThreatCategory),
  'treatmentPlanReviewDate' : IDL.Opt(IDL.Text),
  'treatmentPlanDescription' : IDL.Opt(IDL.Text),
  'likelihood' : IDL.Opt(IDL.Nat),
  'treatmentPlanTargetDate' : IDL.Opt(IDL.Text),
  'status' : IDL.Opt(RiskStatus),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addUploadedDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'approveTenantUser' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserToTenant' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'createComplianceControl' : IDL.Func(
      [CreateComplianceControlInput],
      [IDL.Nat],
      [],
    ),
  'createGovernanceItem' : IDL.Func([CreateGovernanceItemInput], [IDL.Nat], []),
  'createRisk' : IDL.Func([CreateRiskInput], [IDL.Nat], []),
  'createTenant' : IDL.Func([TenantCreateInput], [IDL.Nat], []),
  'deleteGovernanceAttachment' : IDL.Func([IDL.Nat], [], []),
  'deleteGovernanceFrameworkMapping' : IDL.Func([IDL.Nat], [], []),
  'deleteGovernanceItem' : IDL.Func([IDL.Nat], [], []),
  'deleteRisk' : IDL.Func([IDL.Nat], [], []),
  'deleteTenant' : IDL.Func([IDL.Nat], [], []),
  'deleteUploadedDocument' : IDL.Func([IDL.Nat], [], []),
  'getCallerTenant' : IDL.Func([], [IDL.Opt(Tenant)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplianceControls' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ComplianceControl)],
      ['query'],
    ),
  'getComplianceFrameworks' : IDL.Func(
      [],
      [IDL.Vec(ComplianceFramework)],
      ['query'],
    ),
  'getComplianceScores' : IDL.Func([], [IDL.Vec(ComplianceScores)], ['query']),
  'getGovernanceAttachment' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(GovAttachmentMeta)],
      ['query'],
    ),
  'getGovernanceAttachments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, GovAttachmentMeta))],
      ['query'],
    ),
  'getGovernanceFrameworkMappings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, GovFrameworkMapping))],
      ['query'],
    ),
  'getGovernanceItems' : IDL.Func([], [IDL.Vec(GovernanceItem)], ['query']),
  'getGovernanceSummary' : IDL.Func([], [GovernanceSummary], ['query']),
  'getRiskById' : IDL.Func([IDL.Nat], [IDL.Opt(RiskItem)], ['query']),
  'getRiskStats' : IDL.Func([], [RiskStats], ['query']),
  'getRisks' : IDL.Func([], [IDL.Vec(RiskItem)], ['query']),
  'getRisksByTenant' : IDL.Func([IDL.Nat], [IDL.Vec(RiskItem)], ['query']),
  'getSSOConfig' : IDL.Func([], [SSOConfig], ['query']),
  'getTenantOrg' : IDL.Func([IDL.Text], [IDL.Opt(TenantOrg)], ['query']),
  'getUploadedDocuments' : IDL.Func(
      [],
      [IDL.Vec(UploadedDocumentMeta)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTenant' : IDL.Func([IDL.Principal], [IDL.Opt(Tenant)], ['query']),
  'initializeGRCData' : IDL.Func([], [], []),
  'initializeISMSRepository' : IDL.Func([], [], []),
  'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listTenantUsers' : IDL.Func([], [IDL.Vec(TenantUser)], ['query']),
  'listTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
  'registerTenantUser' : IDL.Func(
      [UserRegistrationInput],
      [RegistrationResult],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setGovernanceAttachment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'setGovernanceFrameworkMapping' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'setSSOConfig' : IDL.Func([SSOConfig], [], []),
  'tenantLogin' : IDL.Func([IDL.Text, IDL.Text], [TenantLoginResult], []),
  'updateComplianceControl' : IDL.Func(
      [UpdateComplianceControlInput],
      [ComplianceControl],
      [],
    ),
  'updateGovernanceItem' : IDL.Func(
      [UpdateGovernanceItemInput],
      [GovernanceItem],
      [],
    ),
  'updateRisk' : IDL.Func([UpdateRiskInput], [RiskItem], []),
  'createRiskAsTenantUser' : IDL.Func([IDL.Text, CreateRiskInput], [IDL.Nat], []),
  'getRisksAsTenantUser' : IDL.Func([IDL.Text], [IDL.Vec(RiskItem)], ['query']),
  'updateRiskAsTenantUser' : IDL.Func([IDL.Text, UpdateRiskInput], [RiskItem], []),
  'deleteRiskAsTenantUser' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getTenantUsersForDomain' : IDL.Func([IDL.Text], [IDL.Vec(TenantUser)], ['query']),
  'updateTenantUserRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getLicenseKeyStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'setLicenseKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'claimPlatformAdminWithKey' : IDL.Func([IDL.Text], [IDL.Variant({'ok': IDL.Null, 'err': IDL.Text})], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ControlStatus = IDL.Variant({
    'notImplemented' : IDL.Null,
    'partiallyImplemented' : IDL.Null,
    'fullyImplemented' : IDL.Null,
    'notApplicable' : IDL.Null,
  });
  const CreateComplianceControlInput = IDL.Record({
    'status' : ControlStatus,
    'controlName' : IDL.Text,
    'owner' : IDL.Text,
    'description' : IDL.Text,
    'frameworkId' : IDL.Nat,
    'controlId' : IDL.Text,
    'evidence' : IDL.Text,
  });
  const GovernanceCategory = IDL.Variant({
    'actionItem' : IDL.Null,
    'committee' : IDL.Null,
    'meeting' : IDL.Null,
    'policy' : IDL.Null,
  });
  const CreateGovernanceItemInput = IDL.Record({
    'title' : IDL.Text,
    'owner' : IDL.Text,
    'approvedBy' : IDL.Text,
    'reviewDate' : IDL.Text,
    'description' : IDL.Text,
    'category' : GovernanceCategory,
  });
  const RiskTreatment = IDL.Variant({
    'accept' : IDL.Null,
    'avoid' : IDL.Null,
    'mitigate' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const MaturityLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'veryLow' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MitigationControl = IDL.Record({
    'controlName' : IDL.Text,
    'maturityLevel' : MaturityLevel,
    'controlId' : IDL.Text,
  });
  const ThreatCategory = IDL.Variant({
    'nonHostileOutsiders' : IDL.Null,
    'hostileInsiders' : IDL.Null,
    'legal' : IDL.Null,
    'dependencyProblems' : IDL.Null,
    'hostileOutsiders' : IDL.Null,
    'environmental' : IDL.Null,
    'technicalProblems' : IDL.Null,
    'nonHostileInsiders' : IDL.Null,
  });
  const CreateRiskInput = IDL.Record({
    'treatmentNotes' : IDL.Text,
    'impact' : IDL.Nat,
    'title' : IDL.Text,
    'treatment' : RiskTreatment,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'mitigationControls' : IDL.Vec(MitigationControl),
    'vulnerability' : IDL.Text,
    'treatmentOwner' : IDL.Text,
    'treatmentPlanOwner' : IDL.Text,
    'threatCategory' : ThreatCategory,
    'treatmentPlanReviewDate' : IDL.Text,
    'treatmentPlanDescription' : IDL.Text,
    'likelihood' : IDL.Nat,
    'treatmentPlanTargetDate' : IDL.Text,
    'status' : IDL.Opt(IDL.Variant({'open': IDL.Null, 'closed': IDL.Null, 'inTreatment': IDL.Null})),
  });
  const TenantCreateInput = IDL.Record({
    'domain' : IDL.Text,
    'name' : IDL.Text,
  });
  const Tenant = IDL.Record({
    'id' : IDL.Nat,
    'domain' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const ComplianceControl = IDL.Record({
    'id' : IDL.Nat,
    'status' : ControlStatus,
    'controlName' : IDL.Text,
    'owner' : IDL.Text,
    'description' : IDL.Text,
    'frameworkId' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'controlId' : IDL.Text,
    'evidence' : IDL.Text,
  });
  const ComplianceFramework = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'version' : IDL.Text,
  });
  const ComplianceScores = IDL.Record({
    'frameworkName' : IDL.Text,
    'total' : IDL.Nat,
    'score' : IDL.Nat,
    'implemented' : IDL.Nat,
  });
  const GovAttachmentMeta = IDL.Record({
    'blobUrl' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadedAt' : IDL.Int,
  });
  const GovFrameworkMapping = IDL.Record({
    'frameworkName' : IDL.Text,
    'frameworkId' : IDL.Nat,
  });
  const GovernanceStatus = IDL.Variant({
    'active' : IDL.Null,
    'underReview' : IDL.Null,
    'draft' : IDL.Null,
    'retired' : IDL.Null,
  });
  const GovernanceItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : GovernanceStatus,
    'title' : IDL.Text,
    'owner' : IDL.Text,
    'approvedBy' : IDL.Text,
    'createdAt' : IDL.Int,
    'reviewDate' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'category' : GovernanceCategory,
  });
  const GovernanceSummary = IDL.Record({
    'total' : IDL.Nat,
    'byStatus' : IDL.Vec(IDL.Tuple(GovernanceStatus, IDL.Nat)),
    'byCategory' : IDL.Vec(IDL.Tuple(GovernanceCategory, IDL.Nat)),
  });
  const RiskStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inTreatment' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RiskItem = IDL.Record({
    'id' : IDL.Nat,
    'treatmentNotes' : IDL.Text,
    'status' : RiskStatus,
    'impact' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'treatment' : RiskTreatment,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'mitigationControls' : IDL.Vec(MitigationControl),
    'tenantId' : IDL.Nat,
    'residualRiskScore' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'vulnerability' : IDL.Text,
    'treatmentOwner' : IDL.Text,
    'treatmentPlanOwner' : IDL.Text,
    'threatCategory' : ThreatCategory,
    'treatmentPlanReviewDate' : IDL.Text,
    'inherentRiskScore' : IDL.Nat,
    'treatmentPlanDescription' : IDL.Text,
    'likelihood' : IDL.Nat,
    'riskLevel' : RiskLevel,
    'treatmentPlanTargetDate' : IDL.Text,
  });
  const RiskStats = IDL.Record({
    'avgResidualScore' : IDL.Nat,
    'total' : IDL.Nat,
    'byLevel' : IDL.Vec(IDL.Tuple(RiskLevel, IDL.Nat)),
    'avgInherentScore' : IDL.Nat,
    'byStatus' : IDL.Vec(IDL.Tuple(RiskStatus, IDL.Nat)),
  });
  const SSOConfig = IDL.Record({
    'idpIssuerUrl' : IDL.Text,
    'idpClientId' : IDL.Text,
    'allowedDomains' : IDL.Vec(IDL.Text),
    'enabled' : IDL.Bool,
    'notes' : IDL.Text,
    'idpName' : IDL.Text,
    'requireDomainWhitelist' : IDL.Bool,
  });
  const TenantOrg = IDL.Record({
    'id' : IDL.Text,
    'domain' : IDL.Text,
    'createdAt' : IDL.Int,
    'companyName' : IDL.Text,
  });
  const UploadedDocumentMeta = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'blobUrl' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadedAt' : IDL.Int,
    'clauseNumber' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const TenantUser = IDL.Record({
    'id' : IDL.Text,
    'domain' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'approved' : IDL.Bool,
    'companyName' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const UserRegistrationInput = IDL.Record({
    'domain' : IDL.Text,
    'password' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const RegistrationResult = IDL.Variant({
    'ok' : IDL.Null,
    'userAlreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'domainAlreadyRegistered' : IDL.Null,
  });
  const TenantUserLoginResponse = IDL.Record({
    'id' : IDL.Text,
    'domain' : IDL.Text,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const TenantLoginResult = IDL.Variant({
    'ok' : TenantUserLoginResponse,
    'invalidEmail' : IDL.Null,
    'userNotFound' : IDL.Null,
    'invalidPassword' : IDL.Null,
    'internalError' : IDL.Null,
    'notApproved' : IDL.Null,
  });
  const UpdateComplianceControlInput = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Opt(ControlStatus),
    'owner' : IDL.Opt(IDL.Text),
    'evidence' : IDL.Opt(IDL.Text),
  });
  const UpdateGovernanceItemInput = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Opt(GovernanceStatus),
    'title' : IDL.Opt(IDL.Text),
    'owner' : IDL.Opt(IDL.Text),
    'approvedBy' : IDL.Opt(IDL.Text),
    'reviewDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(GovernanceCategory),
  });
  const UpdateRiskInput = IDL.Record({
    'id' : IDL.Nat,
    'treatmentNotes' : IDL.Opt(IDL.Text),
    'impact' : IDL.Opt(IDL.Nat),
    'title' : IDL.Opt(IDL.Text),
    'treatment' : IDL.Opt(RiskTreatment),
    'dueDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'mitigationControls' : IDL.Opt(IDL.Vec(MitigationControl)),
    'vulnerability' : IDL.Opt(IDL.Text),
    'treatmentOwner' : IDL.Opt(IDL.Text),
    'treatmentPlanOwner' : IDL.Opt(IDL.Text),
    'threatCategory' : IDL.Opt(ThreatCategory),
    'treatmentPlanReviewDate' : IDL.Opt(IDL.Text),
    'treatmentPlanDescription' : IDL.Opt(IDL.Text),
    'likelihood' : IDL.Opt(IDL.Nat),
    'treatmentPlanTargetDate' : IDL.Opt(IDL.Text),
    'status' : IDL.Opt(RiskStatus),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addUploadedDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'approveTenantUser' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserToTenant' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'createComplianceControl' : IDL.Func(
        [CreateComplianceControlInput],
        [IDL.Nat],
        [],
      ),
    'createGovernanceItem' : IDL.Func(
        [CreateGovernanceItemInput],
        [IDL.Nat],
        [],
      ),
    'createRisk' : IDL.Func([CreateRiskInput], [IDL.Nat], []),
    'createTenant' : IDL.Func([TenantCreateInput], [IDL.Nat], []),
    'deleteGovernanceAttachment' : IDL.Func([IDL.Nat], [], []),
    'deleteGovernanceFrameworkMapping' : IDL.Func([IDL.Nat], [], []),
    'deleteGovernanceItem' : IDL.Func([IDL.Nat], [], []),
    'deleteRisk' : IDL.Func([IDL.Nat], [], []),
    'deleteTenant' : IDL.Func([IDL.Nat], [], []),
    'deleteUploadedDocument' : IDL.Func([IDL.Nat], [], []),
    'getCallerTenant' : IDL.Func([], [IDL.Opt(Tenant)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplianceControls' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ComplianceControl)],
        ['query'],
      ),
    'getComplianceFrameworks' : IDL.Func(
        [],
        [IDL.Vec(ComplianceFramework)],
        ['query'],
      ),
    'getComplianceScores' : IDL.Func(
        [],
        [IDL.Vec(ComplianceScores)],
        ['query'],
      ),
    'getGovernanceAttachment' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(GovAttachmentMeta)],
        ['query'],
      ),
    'getGovernanceAttachments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, GovAttachmentMeta))],
        ['query'],
      ),
    'getGovernanceFrameworkMappings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, GovFrameworkMapping))],
        ['query'],
      ),
    'getGovernanceItems' : IDL.Func([], [IDL.Vec(GovernanceItem)], ['query']),
    'getGovernanceSummary' : IDL.Func([], [GovernanceSummary], ['query']),
    'getRiskById' : IDL.Func([IDL.Nat], [IDL.Opt(RiskItem)], ['query']),
    'getRiskStats' : IDL.Func([], [RiskStats], ['query']),
    'getRisks' : IDL.Func([], [IDL.Vec(RiskItem)], ['query']),
    'getRisksByTenant' : IDL.Func([IDL.Nat], [IDL.Vec(RiskItem)], ['query']),
    'getSSOConfig' : IDL.Func([], [SSOConfig], ['query']),
    'getTenantOrg' : IDL.Func([IDL.Text], [IDL.Opt(TenantOrg)], ['query']),
    'getUploadedDocuments' : IDL.Func(
        [],
        [IDL.Vec(UploadedDocumentMeta)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTenant' : IDL.Func([IDL.Principal], [IDL.Opt(Tenant)], ['query']),
    'initializeGRCData' : IDL.Func([], [], []),
    'initializeISMSRepository' : IDL.Func([], [], []),
    'isAdminAssigned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listTenantUsers' : IDL.Func([], [IDL.Vec(TenantUser)], ['query']),
    'listTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
    'registerTenantUser' : IDL.Func(
        [UserRegistrationInput],
        [RegistrationResult],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setGovernanceAttachment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'setGovernanceFrameworkMapping' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'setSSOConfig' : IDL.Func([SSOConfig], [], []),
    'tenantLogin' : IDL.Func([IDL.Text, IDL.Text], [TenantLoginResult], []),
    'updateComplianceControl' : IDL.Func(
        [UpdateComplianceControlInput],
        [ComplianceControl],
        [],
      ),
    'updateGovernanceItem' : IDL.Func(
        [UpdateGovernanceItemInput],
        [GovernanceItem],
        [],
      ),
    'updateRisk' : IDL.Func([UpdateRiskInput], [RiskItem], []),
    'createRiskAsTenantUser' : IDL.Func([IDL.Text, CreateRiskInput], [IDL.Nat], []),
    'getRisksAsTenantUser' : IDL.Func([IDL.Text], [IDL.Vec(RiskItem)], ['query']),
    'updateRiskAsTenantUser' : IDL.Func([IDL.Text, UpdateRiskInput], [RiskItem], []),
    'deleteRiskAsTenantUser' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getTenantUsersForDomain' : IDL.Func([IDL.Text], [IDL.Vec(TenantUser)], ['query']),
    'updateTenantUserRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getLicenseKeyStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'setLicenseKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'claimPlatformAdminWithKey' : IDL.Func([IDL.Text], [IDL.Variant({'ok': IDL.Null, 'err': IDL.Text})], []),
    'getGovernanceItemsAsTenantUser' : IDL.Func([IDL.Text], [IDL.Vec(GovernanceItem)], ['query']),
    'createGovernanceItemAsTenantUser' : IDL.Func([IDL.Text, CreateGovernanceItemInput], [IDL.Nat], []),
    'updateGovernanceItemAsTenantUser' : IDL.Func([IDL.Text, UpdateGovernanceItemInput], [GovernanceItem], []),
    'getComplianceControlsAsTenantUser' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(ComplianceControl)], ['query']),
    'createComplianceControlAsTenantUser' : IDL.Func([IDL.Text, CreateComplianceControlInput], [IDL.Nat], []),
    'createTenantUserByAdmin' : IDL.Func([IDL.Record({'fullName': IDL.Text, 'email': IDL.Text, 'password': IDL.Text, 'companyName': IDL.Text, 'domain': IDL.Text, 'role': IDL.Text})], [RegistrationResult], []),
    'listTenantOrgs' : IDL.Func([], [IDL.Vec(TenantOrg)], ['query']),
    'isPlatformSetupDone' : IDL.Func([], [IDL.Bool], ['query']),
    'getTenantSettings' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Record({'domain': IDL.Text, 'companyName': IDL.Text, 'industry': IDL.Text, 'activeFrameworks': IDL.Vec(IDL.Text), 'riskAppetite': IDL.Record({'lowThreshold': IDL.Nat, 'mediumThreshold': IDL.Nat, 'highThreshold': IDL.Nat}), 'onboardingDone': IDL.Bool}))], ['query']),
    'saveTenantSettings' : IDL.Func([IDL.Record({'domain': IDL.Text, 'companyName': IDL.Text, 'industry': IDL.Text, 'activeFrameworks': IDL.Vec(IDL.Text), 'riskAppetite': IDL.Record({'lowThreshold': IDL.Nat, 'mediumThreshold': IDL.Nat, 'highThreshold': IDL.Nat}), 'onboardingDone': IDL.Bool})], [IDL.Bool], []),
    'saveTenantSettingsByAdmin' : IDL.Func([IDL.Record({'domain': IDL.Text, 'companyName': IDL.Text, 'industry': IDL.Text, 'activeFrameworks': IDL.Vec(IDL.Text), 'riskAppetite': IDL.Record({'lowThreshold': IDL.Nat, 'mediumThreshold': IDL.Nat, 'highThreshold': IDL.Nat}), 'onboardingDone': IDL.Bool})], [IDL.Bool], []),
    'saveTenantSettingsAsTenantUser' : IDL.Func([IDL.Text, IDL.Record({'domain': IDL.Text, 'companyName': IDL.Text, 'industry': IDL.Text, 'activeFrameworks': IDL.Vec(IDL.Text), 'riskAppetite': IDL.Record({'lowThreshold': IDL.Nat, 'mediumThreshold': IDL.Nat, 'highThreshold': IDL.Nat}), 'onboardingDone': IDL.Bool})], [IDL.Bool], []),
    'completeTenantOnboarding' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [IDL.Bool], []),
    'isTenantOnboardingDone' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'setControlGovernanceLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [IDL.Bool], []),
    'getControlGovernanceLinks' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Record({'tenantDomain': IDL.Text, 'controlId': IDL.Text, 'governanceItemIds': IDL.Vec(IDL.Text)}))], ['query']),
    'getControlGovernanceLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Record({'tenantDomain': IDL.Text, 'controlId': IDL.Text, 'governanceItemIds': IDL.Vec(IDL.Text)}))], ['query']),
    'getGovernanceAttachmentsAsTenantUser' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Tuple(IDL.Nat, GovAttachmentMeta))], ['query']),
    'getGovernanceFrameworkMappingsAsTenantUser' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Tuple(IDL.Nat, GovFrameworkMapping))], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
