/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ComplianceControl {
  'id' : bigint,
  'status' : ControlStatus,
  'controlName' : string,
  'owner' : string,
  'description' : string,
  'frameworkId' : bigint,
  'updatedAt' : bigint,
  'controlId' : string,
  'evidence' : string,
}
export interface ComplianceFramework {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'version' : string,
}
export interface ComplianceScores {
  'frameworkName' : string,
  'total' : bigint,
  'score' : bigint,
  'implemented' : bigint,
}
export type ControlStatus = { 'notImplemented' : null } |
  { 'partiallyImplemented' : null } |
  { 'fullyImplemented' : null } |
  { 'notApplicable' : null };
export interface CreateComplianceControlInput {
  'status' : ControlStatus,
  'controlName' : string,
  'owner' : string,
  'description' : string,
  'frameworkId' : bigint,
  'controlId' : string,
  'evidence' : string,
}
export interface CreateGovernanceItemInput {
  'title' : string,
  'owner' : string,
  'approvedBy' : string,
  'reviewDate' : string,
  'description' : string,
  'category' : GovernanceCategory,
}
export interface CreateRiskInput {
  'treatmentNotes' : string,
  'impact' : bigint,
  'title' : string,
  'treatment' : RiskTreatment,
  'dueDate' : string,
  'description' : string,
  'mitigationControls' : Array<MitigationControl>,
  'vulnerability' : string,
  'treatmentOwner' : string,
  'treatmentPlanOwner' : string,
  'threatCategory' : ThreatCategory,
  'treatmentPlanReviewDate' : string,
  'treatmentPlanDescription' : string,
  'likelihood' : bigint,
  'treatmentPlanTargetDate' : string,
}
export interface GovAttachmentMeta {
  'blobUrl' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'uploadedAt' : bigint,
}
export interface GovFrameworkMapping {
  'frameworkName' : string,
  'frameworkId' : bigint,
}
export type GovernanceCategory = { 'actionItem' : null } |
  { 'committee' : null } |
  { 'meeting' : null } |
  { 'policy' : null };
export interface GovernanceItem {
  'id' : bigint,
  'status' : GovernanceStatus,
  'title' : string,
  'owner' : string,
  'approvedBy' : string,
  'createdAt' : bigint,
  'reviewDate' : string,
  'description' : string,
  'updatedAt' : bigint,
  'category' : GovernanceCategory,
}
export type GovernanceStatus = { 'active' : null } |
  { 'underReview' : null } |
  { 'draft' : null } |
  { 'retired' : null };
export interface GovernanceSummary {
  'total' : bigint,
  'byStatus' : Array<[GovernanceStatus, bigint]>,
  'byCategory' : Array<[GovernanceCategory, bigint]>,
}
export type MaturityLevel = { 'low' : null } |
  { 'high' : null } |
  { 'veryLow' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface MitigationControl {
  'controlName' : string,
  'maturityLevel' : MaturityLevel,
  'controlId' : string,
}
export type RegistrationResult = { 'ok' : null } |
  { 'userAlreadyExists' : null } |
  { 'invalidInput' : null } |
  { 'domainAlreadyRegistered' : null };
export interface RiskItem {
  'id' : bigint,
  'treatmentNotes' : string,
  'status' : RiskStatus,
  'impact' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'treatment' : RiskTreatment,
  'dueDate' : string,
  'description' : string,
  'mitigationControls' : Array<MitigationControl>,
  'tenantId' : bigint,
  'residualRiskScore' : bigint,
  'updatedAt' : bigint,
  'vulnerability' : string,
  'treatmentOwner' : string,
  'treatmentPlanOwner' : string,
  'threatCategory' : ThreatCategory,
  'treatmentPlanReviewDate' : string,
  'inherentRiskScore' : bigint,
  'treatmentPlanDescription' : string,
  'likelihood' : bigint,
  'riskLevel' : RiskLevel,
  'treatmentPlanTargetDate' : string,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface RiskStats {
  'avgResidualScore' : bigint,
  'total' : bigint,
  'byLevel' : Array<[RiskLevel, bigint]>,
  'avgInherentScore' : bigint,
  'byStatus' : Array<[RiskStatus, bigint]>,
}
export type RiskStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'inTreatment' : null };
export type RiskTreatment = { 'accept' : null } |
  { 'avoid' : null } |
  { 'mitigate' : null } |
  { 'transfer' : null };
export interface SSOConfig {
  'idpIssuerUrl' : string,
  'idpClientId' : string,
  'allowedDomains' : Array<string>,
  'enabled' : boolean,
  'notes' : string,
  'idpName' : string,
  'requireDomainWhitelist' : boolean,
}
export interface Tenant {
  'id' : bigint,
  'domain' : string,
  'ownerPrincipal' : Principal,
  'name' : string,
  'createdAt' : bigint,
}
export interface TenantCreateInput { 'domain' : string, 'name' : string }
export type TenantLoginResult = { 'ok' : TenantUserLoginResponse } |
  { 'invalidEmail' : null } |
  { 'userNotFound' : null } |
  { 'invalidPassword' : null } |
  { 'internalError' : null } |
  { 'notApproved' : null };
export interface TenantOrg {
  'id' : string,
  'domain' : string,
  'createdAt' : bigint,
  'companyName' : string,
}
export interface TenantUser {
  'id' : string,
  'domain' : string,
  'createdAt' : bigint,
  'role' : string,
  'fullName' : string,
  'email' : string,
  'approved' : boolean,
  'companyName' : string,
  'passwordHash' : string,
}
export interface TenantUserLoginResponse {
  'id' : string,
  'domain' : string,
  'role' : string,
  'fullName' : string,
  'email' : string,
  'companyName' : string,
}
export type ThreatCategory = { 'nonHostileOutsiders' : null } |
  { 'hostileInsiders' : null } |
  { 'legal' : null } |
  { 'dependencyProblems' : null } |
  { 'hostileOutsiders' : null } |
  { 'environmental' : null } |
  { 'technicalProblems' : null } |
  { 'nonHostileInsiders' : null };
export interface UpdateComplianceControlInput {
  'id' : bigint,
  'status' : [] | [ControlStatus],
  'owner' : [] | [string],
  'evidence' : [] | [string],
}
export interface UpdateGovernanceItemInput {
  'id' : bigint,
  'status' : [] | [GovernanceStatus],
  'title' : [] | [string],
  'owner' : [] | [string],
  'approvedBy' : [] | [string],
  'reviewDate' : [] | [string],
  'description' : [] | [string],
  'category' : [] | [GovernanceCategory],
}
export interface UpdateRiskInput {
  'id' : bigint,
  'treatmentNotes' : [] | [string],
  'impact' : [] | [bigint],
  'title' : [] | [string],
  'treatment' : [] | [RiskTreatment],
  'dueDate' : [] | [string],
  'description' : [] | [string],
  'mitigationControls' : [] | [Array<MitigationControl>],
  'vulnerability' : [] | [string],
  'treatmentOwner' : [] | [string],
  'treatmentPlanOwner' : [] | [string],
  'threatCategory' : [] | [ThreatCategory],
  'treatmentPlanReviewDate' : [] | [string],
  'treatmentPlanDescription' : [] | [string],
  'likelihood' : [] | [bigint],
  'treatmentPlanTargetDate' : [] | [string],
  'status' : [] | [RiskStatus],
}
export interface UploadedDocumentMeta {
  'id' : bigint,
  'title' : string,
  'blobUrl' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'uploadedAt' : bigint,
  'clauseNumber' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'department' : string,
}
export interface UserRegistrationInput {
  'domain' : string,
  'password' : string,
  'fullName' : string,
  'email' : string,
  'companyName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addUploadedDocument' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
  'approveTenantUser' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserToTenant' : ActorMethod<[Principal, bigint], undefined>,
  'createComplianceControl' : ActorMethod<
    [CreateComplianceControlInput],
    bigint
  >,
  'createGovernanceItem' : ActorMethod<[CreateGovernanceItemInput], bigint>,
  'createRisk' : ActorMethod<[CreateRiskInput], bigint>,
  'createTenant' : ActorMethod<[TenantCreateInput], bigint>,
  'deleteGovernanceAttachment' : ActorMethod<[bigint], undefined>,
  'deleteGovernanceFrameworkMapping' : ActorMethod<[bigint], undefined>,
  'deleteGovernanceItem' : ActorMethod<[bigint], undefined>,
  'deleteRisk' : ActorMethod<[bigint], undefined>,
  'deleteTenant' : ActorMethod<[bigint], undefined>,
  'deleteUploadedDocument' : ActorMethod<[bigint], undefined>,
  'getCallerTenant' : ActorMethod<[], [] | [Tenant]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplianceControls' : ActorMethod<[bigint], Array<ComplianceControl>>,
  'getComplianceFrameworks' : ActorMethod<[], Array<ComplianceFramework>>,
  'getComplianceScores' : ActorMethod<[], Array<ComplianceScores>>,
  'getGovernanceAttachment' : ActorMethod<[bigint], [] | [GovAttachmentMeta]>,
  'getGovernanceAttachments' : ActorMethod<
    [],
    Array<[bigint, GovAttachmentMeta]>
  >,
  'getGovernanceFrameworkMappings' : ActorMethod<
    [],
    Array<[bigint, GovFrameworkMapping]>
  >,
  'getGovernanceItems' : ActorMethod<[], Array<GovernanceItem>>,
  'getGovernanceSummary' : ActorMethod<[], GovernanceSummary>,
  'getRiskById' : ActorMethod<[bigint], [] | [RiskItem]>,
  'getRiskStats' : ActorMethod<[], RiskStats>,
  'getRisks' : ActorMethod<[], Array<RiskItem>>,
  'getRisksByTenant' : ActorMethod<[bigint], Array<RiskItem>>,
  'getSSOConfig' : ActorMethod<[], SSOConfig>,
  'getTenantOrg' : ActorMethod<[string], [] | [TenantOrg]>,
  'getUploadedDocuments' : ActorMethod<[], Array<UploadedDocumentMeta>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTenant' : ActorMethod<[Principal], [] | [Tenant]>,
  'initializeGRCData' : ActorMethod<[], undefined>,
  'initializeISMSRepository' : ActorMethod<[], undefined>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listTenantUsers' : ActorMethod<[], Array<TenantUser>>,
  'listTenants' : ActorMethod<[], Array<Tenant>>,
  'registerTenantUser' : ActorMethod<
    [UserRegistrationInput],
    RegistrationResult
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setGovernanceAttachment' : ActorMethod<
    [bigint, string, bigint, string],
    undefined
  >,
  'setGovernanceFrameworkMapping' : ActorMethod<
    [bigint, bigint, string],
    undefined
  >,
  'setSSOConfig' : ActorMethod<[SSOConfig], undefined>,
  'tenantLogin' : ActorMethod<[string, string], TenantLoginResult>,
  'updateComplianceControl' : ActorMethod<
    [UpdateComplianceControlInput],
    ComplianceControl
  >,
  'updateGovernanceItem' : ActorMethod<
    [UpdateGovernanceItemInput],
    GovernanceItem
  >,
  'updateRisk' : ActorMethod<[UpdateRiskInput], RiskItem>,
  'updateTenantUserRole' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];